NotaVenta/Controllers/VentaController.cs
using NotaVenta.UTIL;
using NotaVenta.UTIL.FilterAttributes;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using UTIL.Models;
using UTIL.Objetos;

namespace NotaVenta.Controllers
{
    public class VentaController : BaseController
    {
        #region Vistas

        public ActionResult Index()
        {
            return View();
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.VENDEDOR)]
        public ActionResult MisClientes()
        {
            UsuariosModels usr = new UsuariosModels();
            ParametrosModels parametros = ObtieneParametros();
            List<ClientesModels> lclientes = new List<ClientesModels>();

            usr.VenCod = codigoVendedorUsuario().Trim();
            usr.id = SessionVariables.SESSION_DATOS_USUARIO.IdUsuario;
            var misClientes = controlDisofi().BuscarMisClientesVenCod(usr, baseDatosUsuario());

            if (misClientes != null)
            {
                lclientes = misClientes;
            }
            ViewBag.parametros = parametros;
            ViewBag.clientes = lclientes;

            IEnumerable<SelectListItem> clientesGiro = controlDisofi().ObtenerGiro(baseDatosUsuario()).Select(c => new SelectListItem()
            {
                Text = c.GirDes,
                Value = c.GirCod
            }).ToList();
            ViewBag.Giro = clientesGiro;

            IEnumerable<SelectListItem> clientesCiudad = controlDisofi().ObtenerCiudad(baseDatosUsuario()).Select(c => new SelectListItem()
            {
                Text = c.CiuDes,
                Value = c.CiuCod
            }).ToList();
            ViewBag.Ciudad = clientesCiudad;

            IEnumerable<SelectListItem> clientesComuna = controlDisofi().ObtenerComuna(baseDatosUsuario()).Select(c => new SelectListItem()
            {
                Text = c.ComDes,
                Value = c.ComCod
            }).ToList();
            ViewBag.Comuna = clientesComuna;

            return View();
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.VENDEDOR)]
        public JsonResult PreNotadeVenta(string CodAux, string NomAux, string RutAux)
        {
            ParametrosModels parametros = ObtieneParametros();
            NotadeVentaCabeceraModels notadeVentaCabeceraModels = new NotadeVentaCabeceraModels();
            notadeVentaCabeceraModels.CodAux = CodAux;
            notadeVentaCabeceraModels.NomAux = NomAux;
            notadeVentaCabeceraModels.RutAux = RutAux;
            SessionVariables.SESSION_NOTA_VENTA_CABECERA_MODEL = notadeVentaCabeceraModels;


            NotadeVentaCabeceraModels NVC = SessionVariables.SESSION_NOTA_VENTA_CABECERA_MODEL;
            NVC.NVNumero = 0;
            NVC.NumOC = "";
            NVC.NumReq = 0;
            var validador = 0;

            ClientesModels cliente = new ClientesModels
            {
                CodAux = NVC.CodAux
            };
            List<ClientesModels> contactoCorreos = controlDisofi().GetContacto(baseDatosUsuario(), cliente);
            List<ClientesModels> clientes = controlDisofi().GetClientes(baseDatosUsuario(), cliente);

            CreditoModel credito = controlDisofi().ObtenerCredito(cliente.CodAux, baseDatosUsuario());

            if (parametros.ManejaLineaCreditoVendedor)
            {
                if (credito != null)
                {
                    credito.Deuda = credito.Debe - credito.Haber;
                    credito.Saldo = (credito.Credito + credito.Deuda);

                    if (credito.Credito == 0)
                    {
                        validador = -999;
                        return Json(validador);
                    }
                    else
                    {
                        validador = 1;
                        return Json(validador);
                    }

                }
            }

            if (contactoCorreos != null && contactoCorreos.Count > 0 && contactoCorreos[0].EMail != "")
            {
                ViewBag.CorreoCliente = contactoCorreos[0].EMail;
                validador = 1;
                return Json(validador);
            }
            else
            {
                if (clientes != null && clientes.Count > 0)
                {
                    if (parametros.EnvioMailCliente && Convert.ToString(clientes[0].EMail).Trim() == "")
                    {
                        validador = -1;
                        return Json(validador);
                    }
                    else
                    {
                        ViewBag.CorreoCliente = clientes[0].EMail;
                        validador = 1;
                        return Json(validador);
                    }
                }
                else
                {
                    validador = -1;
                    return Json(validador);
                }
            }
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.VENDEDOR)]
        public ActionResult NotaDeVenta()
        {
            ParametrosModels parametros = ObtieneParametros();

            ViewBag.Parametros = parametros;

            var id_ = SessionVariables.SESSION_DATOS_USUARIO.IdUsuario.ToString();
            var VenCod = codigoVendedorUsuario();
            var id = id_;

            NotadeVentaCabeceraModels NVC = SessionVariables.SESSION_NOTA_VENTA_CABECERA_MODEL;
            NVC.NVNumero = 0;
            NVC.NumOC = "";
            NVC.NumReq = 0;

            ClientesModels cliente = new ClientesModels
            {
                CodAux = NVC.CodAux,
                RutAux = NVC.RutAux,
            };

            ClientesModels cm = controlDisofi().ObtenerAtributoDescuento(baseDatosUsuario(), cliente.CodAux, parametros.AtributoSoftlandDescuentoCliente);
            cliente.ValorAtributo = cm.ValorAtributo;

            ViewBag.ValorAtributo = cliente.ValorAtributo;
            VendedoresSoftlandModels vendedorCliente = controlDisofi().ObtenerVendedorCliente(cliente.CodAux, baseDatosUsuario());
            ViewBag.VendedorCliente = vendedorCliente;
            CreditoModel credito = controlDisofi().ObtenerCredito(cliente.CodAux, baseDatosUsuario());

            //if (parametros.ManejaLineaCreditoVendedor)
            //{
            //    if (credito != null)
            //    {
            //        credito.Deuda = credito.Debe - credito.Haber;
            //        credito.Saldo = credito.Credito - credito.Deuda;

            //        if (credito.Credito == 0)
            //        {
            //            TempData["Mensaje"] = "CLIENTE NO TIENE CREDITO. <br>";
            //            return RedirectToAction("MisClientes", "Venta");
            //        }

            //    }
            //}



            ViewBag.Credito = credito;
            ViewBag.CodAux = NVC.CodAux;
            ViewBag.RutAux = NVC.RutAux;

            /////
            double MontoTotal = 0;
            double Saldo = 0;
            try
            {
                List<SaldosModel> Saldos = new List<SaldosModel>();
                Saldos = controlDisofi().ObtenerSaldo(ViewBag.RutAux, ViewBag.CodAux, baseDatosUsuario());

                foreach (SaldosModel item in Saldos)
                {
                    MontoTotal = item.Saldo;
                    Saldo = MontoTotal + Saldo;
                }
            }
            catch (Exception)
            {

                throw;
            }

            ViewBag.SaldoTotal = Saldo;
            /////

            List<ClientesModels> contactoCorreos = controlDisofi().GetContacto(baseDatosUsuario(), cliente);
            List<ClientesModels> clientes = controlDisofi().GetClientes(baseDatosUsuario(), cliente);

            if (contactoCorreos != null && contactoCorreos.Count > 0 && contactoCorreos[0].EMail != "")
            {
                ViewBag.CorreoCliente = contactoCorreos[0].EMail;
            }
            else
            {
                if (clientes != null && clientes.Count > 0 && clientes[0].EMail != "")
                {
                    ViewBag.CorreoCliente = clientes[0].EMail;
                }

            }



            ViewBag.numeronota = NVC;

            CondicionVentasModels conven = new CondicionVentasModels();

            //Se lista(n) la(s) condicion(es) de venta(s)

            List<CondicionVentasModels> lcondicion = new List<CondicionVentasModels>();
            List<CondicionVentasModels> lCondicionCliente = new List<CondicionVentasModels>();

            conven.CodAux = NVC.CodAux.ToString();
            lCondicionCliente = controlDisofi().listarConVen(baseDatosUsuario(), conven);

            if (parametros.MuestraCondicionVentaCliente)
            {
                conven.CodAux = NVC.CodAux.ToString();
                lcondicion = controlDisofi().listarConVen(baseDatosUsuario(), conven);
            }
            else if (parametros.MuestraCondicionVentaTodos)
            {
                conven.CodAux = "-1";
                lcondicion = controlDisofi().listarConVen(baseDatosUsuario(), conven);
            }

            ViewBag.condicion = lcondicion;
            lCondicionCliente = (lCondicionCliente == null) ? new List<CondicionVentasModels>() : lCondicionCliente;

            ViewBag.condicionCliente = lCondicionCliente.Count > 0 ? lCondicionCliente[0] : new CondicionVentasModels();

            ClientesModels contacto = new ClientesModels();

            contacto.CodAux = NVC.CodAux.ToString();
            contacto.NomAux = SessionVariables.SESSION_DATOS_USUARIO.Nombre.ToString();

            //Se ubica la lista de contactos
            List<ClientesModels> contactos = controlDisofi().BuscarContacto(baseDatosUsuario(), contacto);

            if (contactos == null || contactos.Count == 0)
            {
                ViewBag.contactos = contactos;

NotaVenta/Views/Venta/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

NotaVenta/Views/Venta/MisClientes.cshtml
@using UTIL.Models;
@using NotaVenta.UTIL;
@{
    string parametroUpdate = NotaVenta.UTIL.ActualizacionJS.obtenerParametro();
    ViewBag.Title = "Mis Clientes";
    List<ClientesModels> clientes = ViewBag.clientes;
    //var validacion = "$0";
    ParametrosModels parametros = ViewBag.parametros;
    if (((BaseController)this.ViewContext.Controller).codigoVendedorUsuario() == null)
    {
        var URL = System.Configuration.ConfigurationManager.AppSettings.Get("url");
        Response.Redirect(URL);
    }
}

<link href="~/Scripts/css/estilotables.css" rel="stylesheet" />
<script src="~/WebJs/Venta/MisClientes.js?@parametroUpdate"></script>
<style>
    .rojomaldito {
        background: #E49685;
        color: black;
    }
</style>
<body class="contact-page">
    <input type="hidden" id="urlTablaSaldos" value="@Url.Action("ObtenerSaldo", "Reporte")" />
    <div id="content" class="content">
        <input type="hidden" id="urlNotaVenta" value="@Url.Action("NotaDeVenta", "Venta" )" />
        <h1 class="page-header">@ViewBag.Message <small></small></h1>
        <div class="panel panel-inverse width-full">
            <div class="panel-heading">
                <h4 class="panel-title">Listado De Clientes </h4>
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                </div>
            </div>
            <div class="table-responsive">
                @if (parametros.AgregaCliente)
                {
                    <div class="float-right">
                        <br />
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#AgregaCliente">Agregar Cliente</button>
                        <br />
                        <br />
                    </div>
                }
                <table id="dataTable" class="table" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Codigo</th>
                            <th>Cliente</th>
                            <th>Dirección</th>
                            <th>Telefono</th>
                            <th>Notas</th>
                            <th>Nota de Venta</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            try
                            {
                                for (int i = 0; i < clientes.Count; i++)
                                {
                                    <tr>
                                        <td>@clientes[i].CodAux</td>
                                        <td>@clientes[i].NomAux</td>
                                        <td>@clientes[i].DirAux @clientes[i].DirNum</td>
                                        <td>@clientes[i].FonAux1</td>


                                        @if (clientes[i].Notas == null)
                                        {
                                            <td>No cuenta con nota</td>
                                        }
                                        else
                                        {
                                            <td>@clientes[i].Notas</td>
                                        }
                                        <td>
                                            <a class="btn btn-default btn-xs" onclick="PreNotaVenta('@clientes[i].CodAux','@clientes[i].NomAux', '@clientes[i].RutAux')" style="cursor:pointer;" />
                                            <img src="~/Content/Image/guia.png" />
                                            @*<a class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalSaldo" onclick="ObtenerSaldo('@clientes[i].RutAux')" style="cursor:pointer;" />
                                            <img src="~/Content/Image/guia.png" />*@
                                        </td>
                                    </tr>
                                }
                            }
                            catch (Exception)
                            {
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td>Este Usuario no tiene Clientes Asociados</td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <div id="AgregaCliente" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Agregar Cliente</h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="x_content">
                        <br />
                        <div class="form-horizontal form-label-left input_mask">
                            <input type="hidden" name="txtcodAux" id="CodAuxMod">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback">
                                    <label class="control-label"><b>Rut: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="text" required="required" maxlength="12" class="form-control has-feedback-left" id="RutCli" name="txtNombre" placeholder="Rut" oninput="checkRut(this)" maxlength="13">
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <label class="control-label"><b>Giro Cliente: </b></label>
                                    @Html.DropDownList("GirAux", (IEnumerable<SelectListItem>)ViewBag.Giro, "Seleccione Giro", new { @class = "form-control", @id = "GirAux", @name = "GirAux" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                                    <label class="control-label"><b>Nombre: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="text" required="required" maxlength="60" class="form-control has-feedback-left" id="NombreCli" name="txtUsuario" placeholder="Nombre">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback">
                                    <label class="control-label"><b>Email: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="email" required class="form-control" maxlength="250" id="EmailMod" name="EmailCli" placeholder="Email">
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback">
                                    <label class="control-label"><b>Email Dte: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="email" required class="form-control" maxlength="250" id="EmailDteMod" name="EmailCli" placeholder="Email">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                                    <label class="control-label"><b>Direccion: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="text" required class="form-control" maxlength="60" id="DireccioCli" name="Direccion" placeholder="Direccion">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 col-sm-4 col-xs-4 form-group has-feedback">
                                    <label class="control-label"><b>Telefono: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="tel" required class="form-control" maxlength="15" id="TelefonoCli" name="Telefono" placeholder="Telefono">
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-4 form-group has-feedback">
                                    <label class="control-label"><b>Ciudad: </b></label>
                                    @Html.DropDownList("AgregarClienteCiudad", (IEnumerable<SelectListItem>)ViewBag.Ciudad, "Seleccione Ciudad", new { @class = "form-control", @id = "AgregarClienteCiudad", @name = "AgregarClienteCiudad" })
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-4 form-group has-feedback">
                                    <label class="control-label"><b>Comuna: </b></label>
                                    @Html.DropDownList("AgregarClienteComuna", (IEnumerable<SelectListItem>)ViewBag.Comuna, "Seleccione Comuna", new { @class = "form-control", @id = "AgregarClienteComuna", @name = "AgregarClienteComuna" })
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                                    <button class="btn btn-success" type="submit" id="AgregarCliente" onclick="AgregarCliente()">Grabar</button>
                                    <button class="btn btn-primary" type="reset" style="display: none">Resetear</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnCerrarModal" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>


    <a id="AgregarCorreo" style="display: none" href="#modalAddCorreo" class="btn btn-sm btn-success" data-toggle="modal">prueba</a>
    <div class="modal fade" id="modalAddCorreo">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Cliente no tiene Correo Asociado</h4>
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">
                        x
                    </button>
                </div>
                <div class="modal-body">
                    <div class="table-responsive form-inline">
                        <table class="table ">
                            <tbody>
                                <tr class="highlighted">
                                    <td>Agregar Correo:</td>
                                    <td><input type="email" required id="AddCorreo" name="AddCorreo" class="form-control" /></td>
                                </tr>
                            </tbody>
                            <tr>
                                <td></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <a id="btnAgregarCorreo" href="javascript:;" class="btn btn-success">Confirmar</a>
                    <a id="CerrarAddCorreo" href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                </div>
            </div>
        </div>
    </div>

    <div id="modalSaldo" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Detalle Saldo Cliente</h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="x_content">
                        <div class="col-lg-push-12">
                            <div class="table-responsive form-inline">
                                <table id="tblSaldos" class="table table-profile"></table>
                            </div>
                        </div>
                        <br />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnCerrarModal" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

</body>