NotaVenta/Controllers/AdministracionController.cs
using NotaVenta.UTIL;
using NotaVenta.UTIL.Error;
using NotaVenta.UTIL.FilterAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UTIL.Models;
using UTIL.Objetos;
using UTIL.Validaciones;

namespace NotaVenta.Controllers
{
    public class AdministracionController : BaseController
    {
        #region Vistas

        public ActionResult Index()
        {
            return null;
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.ADMINISTRADOR)]
        public ActionResult Usuarios()
        {
            List<UsuariosModels> lUsuarios = controlDisofi().listarUsuarios();
            ViewBag.usuarios = lUsuarios;

            List<UsuariosTiposModels> ltipo = controlDisofi().listarTipo();
            ViewBag.tipo = ltipo;

            //List<VendedoresSoftlandModels> lvendedor = controlDisofi().listarVendedoresSoftland(baseDatosUsuario());
            //ViewBag.vendedor = lvendedor;

            IEnumerable<SelectListItem> lPerfil = controlDisofi().ListarPerfiles().Select(c => new SelectListItem()
            {
                Text = c.TipoUsuario,
                Value = c.ID.ToString()
            }).ToList();
            ViewBag.Perfil = lPerfil;

            IEnumerable<SelectListItem> dataEmpresas = controlDisofi().ListarEmpresas().Select(c => new SelectListItem()
            {
                Text = c.NombreEmpresa,
                Value = c.IdEmpresa.ToString()
            }).ToList();

            ViewBag.Empresas = dataEmpresas;

            return View();
        }



        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.ADMINISTRADOR)]
        public ActionResult Clientes()
        {
            List<ClientesModels> ListClientes = new List<ClientesModels>();
            ParametrosModels parametros = ObtieneParametros();
            ViewBag.parametros = parametros;
            List<EmpresaModel> empresas = controlDisofi().ListarEmpresas();
            ViewBag.empresas = empresas;

            EmpresaModel empresaModel = SessionVariables.SESSION_CLIENTE_BASE_DATOS;
            ViewBag.empresaSeleccionada = empresaModel;
            List<ClientesModels> listClientes = null;
            if (empresaModel != null)
            {
                listClientes = controlDisofi().listarClientes(empresaModel.BaseDatos);
            }

            if (listClientes != null)
            {
                ListClientes = listClientes;
            }

            ViewBag.clientes = ListClientes;

            return View();
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR)]
        public ActionResult Parametros()
        {
            List<EmpresaModel> empresas = controlDisofi().ListarEmpresas();

            if (empresas != null && empresas.Count > 0)
            {
                ParametrosModels para = ObtieneParametros(empresas[0].IdEmpresa);

                ViewBag.Empresas = empresas;
                ViewBag.Parametros = para;
            }
            else
            {
                return AbrirError(Errores.ERRORES.ERROR_LOGIN_1, TipoAccionError.TIPO_ACCION_BTN.IR_LOGIN);
            }

            return View();
        }

        #endregion


        [HttpPost]
        public JsonResult ObtieneParametro(int idEmpresa)
        {
            try
            {
                ParametrosModels parametro = controlDisofi().BuscarParametros(idEmpresa);

                return Json(parametro);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult EditCliente(string rutAux, string codAux)
        {
            try
            {
                if (rutAux == null)
                {
                    return View();
                }

                if (codAux == null) codAux = string.Empty;

                ClientesModels cliente = new ClientesModels();

                cliente.RutAux = rutAux.ToString();
                cliente.CodAux = codAux.ToString();

                List<ClientesModels> bclientes = controlDisofi().BuscarClientes(cliente);

                if (SessionVariables.SESSION_BUSCAR_CLIENTE != null)
                {
                    SessionVariables.SESSION_BUSCAR_CLIENTE = null;
                    SessionVariables.SESSION_BUSCAR_CLIENTE = bclientes;
                }
                else
                {
                    SessionVariables.SESSION_BUSCAR_CLIENTE = bclientes;
                }

                return View();
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public ActionResult EditUsuarios(int idUsuario)
        {
            UsuariosModels Usuario = new UsuariosModels();
            Usuario.id = idUsuario;
            List<UsuariosModels> busuario = controlDisofi().BuscarUsuario(Usuario, baseDatosUsuario());
            ViewBag.buscarusuarios = busuario;

            List<UsuariosTiposModels> ltipo = controlDisofi().listarTipo();
            ViewBag.tipo = ltipo;

            List<VendedoresSoftlandModels> LisVendedoresSoftland = controlDisofi().ListarVendedoresSoftland(busuario[0].VenCod.Trim());
            ViewBag.vendedorSoftland = LisVendedoresSoftland;

            return View();
        }

        [HttpPost]
        public JsonResult Addusuario(string _Usuario, string _Nombre, string _Contrasena, string _Email, string _Perfil)
        {
            if (!string.IsNullOrEmpty(_Usuario) && !string.IsNullOrEmpty(_Nombre) && !string.IsNullOrEmpty(_Contrasena) && !string.IsNullOrEmpty(_Perfil))
            {
                UsuariosModels usuario = new UsuariosModels()
                {
                    Usuario = _Usuario,
                    Nombre = _Nombre,
                    Password = HashMd5.GetMD5(_Contrasena),
                    email = _Email,
                    tipoUsuario = _Perfil
                };
                RespuestaModel result = controlDisofi().AgregarUsuario(usuario);
                return Json(result);
            }
            else
            {
                var result = -666;
                return Json(result);
            }
        }

        public JsonResult CambiarEmpresaCliente(int _IdEmpresa)
        {
            EmpresaModel result = controlDisofi().ListarEmpresas().Where(m => m.IdEmpresa == _IdEmpresa).First();

            SessionVariables.SESSION_CLIENTE_BASE_DATOS = result;

            return (Json(new RespuestaModel() { Verificador = true }));
        }

        public JsonResult EliminarUsuario(int _Id)
        {
            UsuariosModels usuarios = new UsuariosModels();
            usuarios.id = _Id;
            RespuestaModel result = controlDisofi().EliminarUsuario(usuarios);

            return (Json(result));
        }

        public JsonResult EditarUsuario(int _Id, string _Usuario, string _Nombre, string _Contrasena, string _Email, string _Perfil)
        {
            if (!string.IsNullOrEmpty(_Usuario) && !string.IsNullOrEmpty(_Nombre) && !string.IsNullOrEmpty(_Contrasena) && !string.IsNullOrEmpty(_Email) && !string.IsNullOrEmpty(_Perfil))
            {
                UsuariosModels usuarios = new UsuariosModels()
                {
                    id = _Id,
                    Usuario = _Usuario,
                    Nombre = _Nombre,
                    Password = HashMd5.GetMD5(_Contrasena),
                    email = _Email,
                    tipoUsuario = _Perfil
                };
                RespuestaModel result = controlDisofi().EditarUsuario(usuarios, baseDatosUsuario());
                return (Json(result));
            }
            else
            {
                var result = -666;
                return Json(result);
            }
        }

        public JsonResult EditarCliente(string _CodAux, string _Nombre, string _Rut, string _Contacto, string _Email, string _Telefono, string _Direccion)
        {
            if (!string.IsNullOrEmpty(_Nombre) && !string.IsNullOrEmpty(_Rut) && !string.IsNullOrEmpty(_Contacto) && !string.IsNullOrEmpty(_Email) && !string.IsNullOrEmpty(_Direccion))
            {
                ClientesModels cliente = new ClientesModels()
                {
                    CodAux = _CodAux,
                    NomAux = _Nombre,
                    RutAux = _Rut,
                    NomCon = _Contacto,
                    EMail = _Email,
                    FonCon = _Telefono,
                    DirAux = _Direccion
                };
                if (ValidaRut.DigitoVerificador(cliente.RutAux))
                {
                    RespuestaModel result = controlDisofi().ActualizarCliente(cliente, baseDatosUsuario());
                    return Json(result);
                }
                else
                {
                    var result = -999;
                    return Json(result);
                }
            }
            else
            {
                var result = -666;
                return Json(result);
            }
        }

        public JsonResult ObtenerDatosUsuario(string _IdUsuario)
        {
            List<UsuariosModels> usuarios = controlDisofi().GetDatosUsuario(_IdUsuario);
            return Json(new { list = usuarios }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ObtenerVendedoresEmpresa(string _IdEmpresa)
        {
            List<EmpresaModel> empresaModels = controlDisofi().ListarEmpresas().Where(m => m.IdEmpresa == Convert.ToInt32(_IdEmpresa)).ToList();

            if (empresaModels != null && empresaModels.Count > 0)
            {
                List<UsuariosModels> usuarios = controlDisofi().ListarCodVendedorSoft(empresaModels[0].BaseDatos);

                return Json(usuarios, JsonRequestBehavior.AllowGet); ;
            }
            else
            {
                return Json(new List<UsuariosModels>(), JsonRequestBehavior.AllowGet); ;
            }
        }

NotaVenta/Views/Shared/_Layout.cshtml
@{ 
    string parametroUpdate = NotaVenta.UTIL.ActualizacionJS.obtenerParametro();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Nota de Venta</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />

    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="~/Content/assets/css/default/app.min.css" rel="stylesheet" />
    <!-- ================== END BASE CSS STYLE ================== -->
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />

    <!-- ================== BEGIN BASE JS ================== -->
    <script src="~/Content/assets/js/app.min.js?@parametroUpdate"></script>
    <script src="~/Content/assets/js/theme/default.min.js?@parametroUpdate"></script>
    <script src="~/WebJs/Base.js?@parametroUpdate"></script>
    <script src="~/WebJs/EditableClass.js?@parametroUpdate"></script>
    <link href="../assets/plugins/gritter/css/jquery.gritter.css" rel="stylesheet" />
    <!-- ================== END BASE JS ================== -->
</head>
<body>
    <!-- begin #page-loader -->
    <div id="page-loader" class="fade show"><span class="spinner"></span></div>
    <!-- end #page-loader -->
    <!-- begin #page-container -->
    <div id="page-container" class="page-container fade page-without-sidebar page-header-fixed page-with-top-menu">
        <input type="hidden" id="urlSeleccionaEmpresa" value="@Url.Action("SeleccionaEmpresa", "Login" )" />
        <input type="hidden" id="urlHome" value="@Url.Action("Index", "Home" )" />
        <!-- begin #header -->
        <div id="header" class="header navbar-default">
            <!-- begin navbar-header -->
            <div class="navbar-header">
                @if (@NotaVenta.UTIL.SessionVariables.SESSION_DATOS_USUARIO.TipoUsuario == -1)
                {
                    <a href="@Url.Action("Parametros", "Administracion")" class="navbar-brand"><span class="navbar-logo"></span><b>Nota de Venta</b></a>
                }
                else
                {
                    <a href="@Url.Action("Index", "Home")" class="navbar-brand"><span class="navbar-logo"></span><b>Nota de Venta</b></a>
                }
                <button type="button" class="navbar-toggle" data-click="top-menu-toggled">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- end navbar-header -->
            <!-- begin header-nav -->
            <ul class="navbar-nav navbar-right">
                <li class="dropdown navbar-user">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                        <img src="" alt="" />
                        <h4 class="d-none d-md-inline">@NotaVenta.UTIL.SessionVariables.SESSION_DATOS_USUARIO.Nombre <small>Empresa: @NotaVenta.UTIL.SessionVariables.SESSION_DATOS_USUARIO.UsuarioEmpresaModel.NombreEmpresa</small></h4> <b class="caret"></b>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        @if (@NotaVenta.UTIL.SessionVariables.SESSION_DATOS_USUARIO.TipoUsuario != 1)
                        {
                            if (NotaVenta.UTIL.SessionVariables.SESSION_EMPRESAS_USUARIO != null)
                            {
                                <a id="aLayoutCambioEmpresa" href="#modalLayoutEmpresas" class="dropdown-item" data-toggle="modal">Cambiar Empresa</a>
                                <div class="dropdown-divider"></div>
                            }
                        }
                        <a href="@Url.Action("LogOut", "Login")" class="dropdown-item">Cerrar Sesion</a>
                    </div>
                </li>
            </ul>


            <!-- end header-nav -->
        </div>
        <!-- end #header -->
        <!-- begin #top-menu -->
        <div id="top-menu" class="top-menu">
            <!-- begin nav -->
            <ul class="nav">
                @using NotaVenta.Helper
                @Html.Menu()
            </ul>
            <!-- end nav -->
        </div>

        <!-- end #top-menu -->
        <!-- begin #content -->
        <div id="content" class="content">
            @RenderBody()
        </div>
        <!-- end theme-panel -->
        <!-- begin scroll to top btn -->
        <a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
        <!-- end scroll to top btn -->
        <div class="modal fade" id="modalLayoutEmpresas">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Cambio de Empresa</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    </div>
                    <div class="modal-body">
                        <div class="table-responsive form-inline">
                            <table class="table table-profile">
                                <tbody>
                                    <tr class="highlight">
                                        <td>Empresa</td>
                                        <td>
                                            <select id="ddlLayoutEmpresas" class="form-control">
                                                @if (NotaVenta.UTIL.SessionVariables.SESSION_EMPRESAS_USUARIO != null)
                                                {
                                                    foreach (var item in NotaVenta.UTIL.SessionVariables.SESSION_EMPRESAS_USUARIO)
                                                    {
                                                        if (item.IdEmpresa != NotaVenta.UTIL.SessionVariables.SESSION_DATOS_USUARIO.UsuarioEmpresaModel.IdEmpresa)
                                                        {
                                                            <option value="@item.IdEmpresa">
                                                                @item.NombreEmpresa
                                                            </option>
                                                        }
                                                    }
                                                }
                                            </select>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a id="modalLayoutEmpresasAgregar" href="javascript:;" class="btn btn-success">Seleccionar Empresa</a>
                        <a id="modalLayoutEmpresasCerrar" href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end page container -->
    <!-- ================== BEGIN BASE JS ================== -->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/assets/plugins/gritter/js/jquery.gritter.js"></script>
    <script src="~/Content/assets/plugins/sweetalert/dist/sweetalert.min.js"></script>
    <!-- ================== END BASE JS ================== -->
</body>
</html>