NotaVenta/Controllers/ReporteController.cs
using NotaVenta.UTIL;
using NotaVenta.UTIL.FilterAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using UTIL.Models;
using UTIL.Objetos;

namespace NotaVenta.Controllers
{
    public class ReporteController : BaseController
    {
        #region Vistas

        public ActionResult Index()
        {
            return null;
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.ADMINISTRADOR, PERFILES.APROBADOR, PERFILES.VENDEDOR)]
        public ActionResult FacturasPendientes()
        {
            ParametrosModels parametros = ObtieneParametros();

            ViewBag.Parametros = parametros;

            List<NotadeVentaCabeceraModels> doc = new List<NotadeVentaCabeceraModels>();
            string codigoVendedor = obtenerUsuario().TipoUsuario == Convert.ToInt32(PERFILES.APROBADOR) ? "-1" : codigoVendedorUsuario();
            var docPendientes = controlDisofi().listarDocPendientes(baseDatosUsuario(), EmpresaUsuario().IdEmpresa, codigoVendedor);

            if (docPendientes != null)
            {
                doc = docPendientes;
            }

            foreach (var item in doc)
            {
                for (int i = 0; i < doc.Count; i++)
                {
                    List<SaldosModel> Saldos = new List<SaldosModel>();
                    Saldos = controlDisofi().ObtenerSaldo(doc[i].RutAux, doc[i].CodAux, baseDatosUsuario());
                    if (Saldos != null && Saldos.Count > 0)
                    {
                        doc[i].Saldo = 0;
                        foreach (SaldosModel itemSaldo in Saldos)
                        {
                            doc[i].Saldo = doc[i].Saldo + itemSaldo.Saldo;
                        }
                    }
                }
            }


            ViewBag.doc = doc;

            return View();
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.ADMINISTRADOR, PERFILES.APROBADOR, PERFILES.VENDEDOR)]
        public ActionResult FacturasRechazadas()
        {
            List<NotadeVentaCabeceraModels> doc = new List<NotadeVentaCabeceraModels>();
            string codigoVendedor = obtenerUsuario().TipoUsuario == Convert.ToInt32(PERFILES.APROBADOR) ? "-1" : codigoVendedorUsuario();
            var docPendientes = controlDisofi().listarDocRechazadas(baseDatosUsuario(), EmpresaUsuario().IdEmpresa, codigoVendedor);

            if (docPendientes != null)
            {
                doc = docPendientes;
            }

            ViewBag.doc = doc;

            return View();
        }

        [HttpPost]
        public JsonResult FacturasPendientes(int _nvId)
        {
            NotadeVentaCabeceraModels NVC = new NotadeVentaCabeceraModels();
            List<NotadeVentaCabeceraModels> NVCL = new List<NotadeVentaCabeceraModels>();
            NotaDeVentaDetalleModels NVD = new NotaDeVentaDetalleModels();
            List<NotaDeVentaDetalleModels> NVDL = new List<NotaDeVentaDetalleModels>();

            NVC.Id = _nvId;
            NVD.Id = _nvId;

            var nvc = controlDisofi().BuscarNVC(NVC, baseDatosUsuario());

            if (nvc != null)
            {
                NVCL = nvc;
            }
            else
            {
                ViewBag.mensaje = 1;
                ViewBag.NVnum = _nvId;
                return Json(new { Mensaje = ViewBag.mensaje, nvNum = ViewBag.NVnum });
            }

            ViewBag.cabecera = NVCL;

            var nvd = controlDisofi().BuscarNVD(NVD, baseDatosUsuario());

            if (nvd != null)
            {
                NVDL = nvd;
            }

            ViewBag.detalle = NVDL;

            return Json(new { Cabecera = NVCL, Detalle = NVDL, Mensaje = ViewBag.mensaje, NVNumero = ViewBag.NVnum }, JsonRequestBehavior.AllowGet);
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.ADMINISTRADOR, PERFILES.APROBADOR, PERFILES.VENDEDOR)]
        public ActionResult FacturasAprobadas()
        {
            List<NotadeVentaCabeceraModels> doc = new List<NotadeVentaCabeceraModels>();
            string codigoVendedor = obtenerUsuario().TipoUsuario == Convert.ToInt32(PERFILES.APROBADOR) ? "-1" : codigoVendedorUsuario();
            var docAprobados = controlDisofi().listarDocAprobados(baseDatosUsuario(), EmpresaUsuario().IdEmpresa, codigoVendedor);

            ParametrosModels parametros = ObtieneParametros();

            ViewBag.Parametros = parametros;

            if (docAprobados != null)
            {
                doc = docAprobados;
            }

            ViewBag.doc = doc;

            return View();
        }

        [HttpPost]
        public JsonResult FacturasAprobadas(int _nvId)
        {
            NotadeVentaCabeceraModels NVC = new NotadeVentaCabeceraModels();
            List<NotadeVentaCabeceraModels> NVCL = new List<NotadeVentaCabeceraModels>();
            NotaDeVentaDetalleModels NVD = new NotaDeVentaDetalleModels();
            List<NotaDeVentaDetalleModels> NVDL = new List<NotaDeVentaDetalleModels>();

            NVC.Id = _nvId;
            NVD.Id = _nvId;

            var nvc = controlDisofi().BuscarNVC(NVC, baseDatosUsuario());

            if (nvc != null)
            {
                NVCL = nvc;
            }
            else
            {
                ViewBag.mensaje = 1;
                ViewBag.NVnum = _nvId;
                return Json(new { Mensaje = ViewBag.mensaje, nvNum = ViewBag.NVnum });
            }

            ViewBag.cabecera = NVCL;

            var nvd = controlDisofi().BuscarNVD(NVD, baseDatosUsuario());

            if (nvd != null)
            {
                NVDL = nvd;
            }

            ViewBag.detalle = NVDL;

            return Json(new { Cabecera = NVCL, Detalle = NVDL, Mensaje = ViewBag.mensaje, NVNumero = ViewBag.NVnum }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        [HttpPost]
        public JsonResult AprobarNotaVenta(int _nvId)
        {
            NotadeVentaCabeceraModels notaVenta = new NotadeVentaCabeceraModels();

            ParametrosModels para = ObtieneParametros();

            notaVenta.Id = _nvId;

            List<NotadeVentaCabeceraModels> proceso = controlDisofi().actualizaEstado(notaVenta, baseDatosUsuario());

            NotadeVentaCabeceraModels cabecera = controlDisofi().GetCab(_nvId);
            try
            {
                List<string> paraEmail = new List<string>();

                var IdAprobador = SessionVariables.SESSION_DATOS_USUARIO.IdUsuario;

                List<VendedorModels> vendedores = controlDisofi().GetVendedores(baseDatosUsuario(), new VendedorModels { VenCod = cabecera.VenCod });
                List<AprobadorModels> aprobador = controlDisofi().GetAprobador(IdAprobador);
                List<ClientesModels> clientes = controlDisofi().GetClientes(baseDatosUsuario(), new ClientesModels { CodAux = cabecera.CodAux });

                if (para.EnvioMailVendedor)
                {
                    if (vendedores != null && vendedores.Count > 0)
                    {
                        if (vendedores[0].Email != null && vendedores[0].Email != "")
                        {
                            paraEmail.Add(vendedores[0].Email);
                        }
                    }
                }
                if (para.EnvioMailCliente)
                {
                    if (vendedores != null && vendedores.Count > 0)
                    {
                        if (clientes[0].EMail != null && clientes[0].EMail != "")
                        {
                            paraEmail.Add(clientes[0].EMail);
                        }
                    }
                }
                if (para.EnvioMailAprobador)
                {
                    if (vendedores != null && vendedores.Count > 0)
                    {
                        if (vendedores[0].Email != null && vendedores[0].Email != "")
                        {
                            paraEmail.Add(vendedores[0].Email);
                        }
                    }
                }

                if (cabecera.CodiCC != null && cabecera.CodiCC.Trim().Equals("01"))
                {
                    List<string> correoTemporal = System.Configuration.ConfigurationManager.AppSettings["CorreoSantiago"].Split(';').ToList();
                    for (int x = 0; x < correoTemporal.Count; x++)
                    {
                        if (correoTemporal[x] != null && correoTemporal[x] != "")
                        {
                            paraEmail.Add(correoTemporal[x]);
                        }
                    }
                }
                if (cabecera.CodiCC != null && cabecera.CodiCC.Trim().Equals("02"))
                {
                    List<string> correoTemporal = System.Configuration.ConfigurationManager.AppSettings["CorreoConcepcion"].Split(';').ToList();
                    for (int x = 0; x < correoTemporal.Count; x++)
                    {
                        if (correoTemporal[x] != null && correoTemporal[x] != "")
                        {
                            paraEmail.Add(correoTemporal[x]);
                        }
                    }
                }
                if (cabecera.CodiCC != null && cabecera.CodiCC.Trim().Equals("12"))
                {
                    List<string> correoTemporal = System.Configuration.ConfigurationManager.AppSettings["CorreoTemuco"].Split(';').ToList();
                    for (int x = 0; x < correoTemporal.Count; x++)
                    {
                        if (correoTemporal[x] != null && correoTemporal[x] != "")
                        {
                            paraEmail.Add(correoTemporal[x]);
                        }
                    }
                }
                {

NotaVenta/Views/Reporte/FacturasAprobadas.cshtml
@using UTIL.Models;
@using NotaVenta.UTIL;
@{
    string parametroUpdate = NotaVenta.UTIL.ActualizacionJS.obtenerParametro();
    ViewBag.Title = "Facturas Aprobadas";
    List<NotadeVentaCabeceraModels> doc = ViewBag.doc;
    ParametrosModels parametros = ViewBag.Parametros;
}

<link href="~/Scripts/css/estilotables.css" rel="stylesheet" />
<script src="~/WebJs/Reporte/FacturasAprobadas.js?@parametroUpdate"></script>
<div id="content" class="content">
    <input type="hidden" id="ControlaStockProducto" value="@parametros.ControlaStockProducto.ToString()" />
    <input type="hidden" id="MuestraUnidadMedidaProducto" value="@parametros.MuestraUnidadMedidaProducto.ToString()" />
    <input type="hidden" id="DescuentoLineaDirectoSoftland" value="@parametros.DescuentoLineaDirectoSoftland.ToString()" />
    <input type="hidden" id="DescuentoTotalDirectoSoftland" value="@parametros.DescuentoTotalDirectoSoftland.ToString()" />
    <input type="hidden" id="CantidadDescuentosProducto" value="@parametros.CantidadDescuentosProducto.ToString()" />
    <input type="hidden" id="CantidadDescuentosTotalDocumento" value="@parametros.CantidadDescuentosTotalDocumento.ToString()" />
    <h1 class="page-header">@ViewBag.Message <small></small></h1>
    <div class="panel panel-inverse width-full">
        <div class="panel-heading">
            <h4 class="panel-title">Listado De Notas de Venta Aprobadas </h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            </div>
        </div>
        <div class="table-responsive">

            <table id="dataTable" class="table" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nº Int.</th>
                        <th>Cliente</th>
                        <th>RUT</th>
                        <th>Fecha Creacion</th>
                        <th>ListaPrecio</th>
                        <th>Contacto</th>
                        <th>Neto</th>
                        <th>Valor Final</th>
                        <th>Comuna</th>
                        <th>CC</th>
                        <th>Estado</th>
                        <th>NV Softland</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        try
                        {
                            for (int i = 0; i < doc.Count; i++)
                            {
                                        <tr>
                                            <td>@doc[i].Id</td>
                                            <td>@doc[i].NomAux</td>
                                            <td>@doc[i].RutAux</td>
                                            <td>@doc[i].nvFem.ToShortDateString()</td>
                                            @if (@doc[i].CodLista == null)
                                            {
                                                <td>0</td>
                                            }
                                            else
                                            {
                                                <td>@doc[i].CodLista</td>
                                            }
                                            @if (@doc[i].NomCon == null)
                                            {
                                                <td>0</td>
                                            }
                                            else
                                            {
                                                <td>@doc[i].NomCon</td>
                                            }
                                            <td style='text-align: right;'>$@double.Parse(doc[i].nvSubTotal.ToString()).ToString("N0")</td>
                                            <td style='text-align: right;'>$@double.Parse(doc[i].TotalBoleta.ToString()).ToString("N0")</td>
                                        <td>@doc[i].ComDes</td>
                                        <td>@doc[i].DescCC</td>
                                            <td>@doc[i].EstadoNP</td>
                                            <td>@doc[i].RutSolicitante</td>
                                            <td>
                                                @if (doc[i].EstadoNP == "A")
                                                {
                                                    <button class="btn btn-success btn-xs" data-toggle="modal" data-target="#DetalleNotaPedido" onclick="DetalleNotaPedido(@doc[i].Id)">@*<img src="~/Content/Image/zoom.png" />*@Detalle</button>
                                                }

                                    </td>
                                </tr>
                            }
                        }
                        catch (Exception)
                        {
                            <tr>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th>SIN DOCUMENTOS APROBADOS</th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@*</div>
                        <br />
                    </div>
                </div>
            </div>
    </section>*@
<form id="sss" name="sss" action="@Url.Action("FacturasPendientes", "Reportes")">
    <input type="hidden" name="nvnumero" id="nvnumero" value="" />
</form>
@*</div>*@

<div id="DetalleNotaPedido" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Detalle Nota de Pedido</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="x_content">
                    <div class="col-lg-push-12">
                        <div class="table-responsive form-inline">
                            <table id="tblDetalleNotaPedido" class="table table-profile"></table>
                        </div>
                    </div>
                    <br />
                    <div class="col-lg-push-12">
                        <div class="table-responsive form-inline">
                            <table id="tblDetalleNotaPedidoDetalle" class="table table-profile"></table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnCerrarModal" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

NotaVenta/Views/Reporte/FacturasPendientes.cshtml
@using UTIL.Models;
@using NotaVenta.UTIL;
@{
    string parametroUpdate = NotaVenta.UTIL.ActualizacionJS.obtenerParametro();
    ViewBag.Title = "Facturas Pendientes";
    List<NotadeVentaCabeceraModels> doc = ViewBag.doc;
    ParametrosModels parametros = ViewBag.Parametros;
}
<link href="~/Scripts/css/estilotables.css" rel="stylesheet" />
<script src="~/WebJs/Reporte/FacturasPendientes.js?@parametroUpdate"></script>

<div id="content" class="content">
    <input type="hidden" id="urlTablaSaldos" value="@Url.Action("ObtenerSaldo", "Reporte")" />
    <input type="hidden" id="ControlaStockProducto" value="@parametros.ControlaStockProducto.ToString()" />
    <input type="hidden" id="MuestraUnidadMedidaProducto" value="@parametros.MuestraUnidadMedidaProducto.ToString()" />
    <input type="hidden" id="DescuentoLineaDirectoSoftland" value="@parametros.DescuentoLineaDirectoSoftland.ToString()" />
    <input type="hidden" id="DescuentoTotalDirectoSoftland" value="@parametros.DescuentoTotalDirectoSoftland.ToString()" />
    <input type="hidden" id="CantidadDescuentosProducto" value="@parametros.CantidadDescuentosProducto.ToString()" />
    <input type="hidden" id="CantidadDescuentosTotalDocumento" value="@parametros.CantidadDescuentosTotalDocumento.ToString()" />
    <h1 class="page-header">@ViewBag.Message <small></small></h1>
    <div class="panel panel-inverse width-full">
        <div class="panel-heading">
            <h4 class="panel-title">Listado De Notas de Venta Pendientes </h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            </div>
        </div>
        <div class="table-responsive">

            <table id="dataTable" class="table" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nº Int.</th>
                        <th>Cliente</th>
                        <th>RUT</th>
                        <th>Fecha Generada</th>
                        <th>Fecha Entrega</th>
                        <th>ListaPrecio</th>
                        @*<th>Contacto</th>*@
                        <th>Neto</th>
                        <th>Valor Final</th>
                        <th>Comuna</th>
                        <th>C. Costo</th>
                        <th>Estado</th>
                        <th>Saldo Cliente</th>

                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        try
                        {
                            if (doc != null)
                            {
                                for (int i = 0; i < doc.Count; i++)
                                {
                                    <tr>
                                        <td>@doc[i].Id</td>
                                        <td>@doc[i].NomAux</td>
                                        <td>@doc[i].RutAux</td>
                                        <td>@doc[i].nvFem.ToShortDateString()</td>
                                        <th>@doc[i].nvFeEnt.ToShortDateString()</th>
                                        @if (@doc[i].CodLista == null)
                                        {
                                            <td>0</td>
                                        }
                                        else
                                        {
                                            <td>@doc[i].CodLista</td>
                                        }
                                        @*@if (@doc[i].NomCon == null)
                                        {
                                            <td>0</td>
                                        }
                                        else
                                        {
                                            <td>@doc[i].NomCon</td>
                                        }*@
                                        <td style='text-align: right;'>$@double.Parse(doc[i].nvSubTotal.ToString()).ToString("N0")</td>
                                        <td style='text-align: right;'>$@double.Parse(doc[i].TotalBoleta.ToString()).ToString("N0")</td>
                                        <td>@doc[i].ComDes</td>
                                        <td>@doc[i].DescCC</td>
                                        <td>@doc[i].EstadoNP</td>
                                        <td style='text-align: right;'>
                                            @double.Parse(doc[i].Saldo.ToString()).ToString("N0")
                                        <button class="btn-primary btn-xs" data-toggle="modal" data-target="#modalSaldo" onclick="ObtenerSaldo('@doc[i].RutAux','@doc[i].CodAux', '@doc[i].NomAux','@doc[i].Saldo')" style="cursor:pointer;"><i class="fas fa-search"></i></button>
                                        <button class="btn-warning btn-xs" data-toggle="modal" data-target="#modalSaldoDetalle" onclick="ObtenerSaldoDetalle('@doc[i].RutAux','@doc[i].CodAux', '@doc[i].NomAux','@doc[i].Saldo')" style="cursor:pointer;"><i class="fas fa-search"></i></button>
                                    </td>
                                    <td>
                                        @if (doc[i].EstadoNP == "P")
                                        {
                                            <button class="btn btn-info btn-xs" data-toggle="modal" data-target="#DetalleNotaPedido" onclick="DetalleNotaPedido(@doc[i].Id,'@doc[i].RutAux')">@*<img src="~/Content/Image/zoom.png" />*@Detalle</button>
                                            if (NotaVenta.UTIL.SessionVariables.SESSION_DATOS_USUARIO.TipoUsuario != 2)
                                            {
                                                <button class="btn btn-success btn-xs" id="btnAprobar_@doc[i].Id" onclick="AprobarNotaVenta(@doc[i].Id, 'btnAprobar_@doc[i].Id')">Aprobar</button>
                                                <button class="btn btn-danger btn-xs" onclick="RechazarNotaVenta(@doc[i].Id,@doc[i].NVNumero)">Rechazar</button>
                                            }
                                        }
                                        else
                                        {
                                            <button class="btn btn-warning btn-m" data-toggle="modal" data-target="#DetalleNotaPedido" onclick="DetalleNotaPedido(@doc[i].Id)"><img src="~/Content/Image/zoom.png" /></button>
                                            <a>&nbsp;</a>
                                        }

                                    </td>
                                </tr>
                            }
                        }
                    }
                    catch (Exception)
                    {
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th>SIN DOCUMENTOS PENDIENTES</th>
                            @*<th></th>*@
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@*</div>
                <br />
            </div>
        </div>
    </div>*@
@*</section>*@
<form id="sss" name="sss" action="@Url.Action("FacturasPendientes", "Reportes")">
    <input type="hidden" name="nvnumero" id="nvnumero" value="" />
    @*@Html.Hidden("RedirectTo", Url.Action("FacturasPendientes", "Reportes");*@
</form>

<div id="DetalleNotaPedido" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Detalle Nota de Pedido</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="x_content">
                    <div class="col-lg-push-12">
                        <div class="table-responsive form-inline">
                            <table id="tblDetalleNotaPedido" class="table table-profile"></table>
                        </div>
                    </div>
                    <br />
                    <div class="col-lg-push-12">
                        <div class="table-responsive form-inline">
                            <table id="tblDetalleNotaPedidoDetalle" class="table table-profile"></table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnCerrarModal" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<div id="modalSaldo" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalSaldoTitulo">Detalle Saldo Cliente - <small id="modalSaldoSubtitulo"></small></h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="x_content">
                    <div class="col-lg-push-12">
                        <div class="table-responsive form-inline">
                            <table id="modalSaldoTblSaldos" class="table table-profile"></table>
                        </div>
                    </div>
                    <br />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="modalSaldoBtnCerrarModal" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<div id="modalSaldoDetalle" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" style="margin-right: 5%; margin-left: 5%; width: 90%">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalSaldoDetalleTitulo">Detalle Saldo Cliente - <small id="modalSaldoDetalleSubtitulo"></small></h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="x_content">
                    <div class="col-xl-12">
                        <!-- begin nav-tabs -->
                        <ul class="nav nav-pills">
                            <li class="nav-item">
                                <a href="#modalSaldoDetalleSaldos" data-toggle="tab" class="nav-link active">
                                    <span class="d-sm-none">Saldos</span>
                                    <span class="d-sm-block d-none">Saldos</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#modalSaldoDetalleSaldados" data-toggle="tab" class="nav-link">
                                    <span class="d-sm-none">Documentos Saldados</span>
                                    <span class="d-sm-block d-none">Documentos Pagados</span>
                                </a>
                            </li>
                        </ul>
                        <!-- end nav-tabs -->
                        <!-- begin tab-content -->
                        <div class="tab-content">
                            <!-- begin tab-pane -->
                            <div class="tab-pane fade active show" id="modalSaldoDetalleSaldos">
                                <br />
                                <div class="table-responsive form-inline">
                                    <table id="modalSaldoDetalleTblSaldos" class="table table-profile"></table>
                                </div>
                            </div>
                            <!-- end tab-pane -->
                            <!-- begin tab-pane -->
                            <div class="tab-pane fade" id="modalSaldoDetalleSaldados">
                                <br />
                                <div class="table-responsive form-inline">
                                    <table id="modalSaldoDetalleTblSaldosDocumentosSaldados" class="table table-profile"></table>
                                </div>
                            </div>
                            <!-- end tab-pane -->
                        </div>
                        <!-- end tab-content -->
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="modalSaldoDetalleBtnCerrarModal" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

NotaVenta/Views/Reporte/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>